# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-09 13:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('condition', models.BooleanField()),
                ('delivery', models.BooleanField()),
                ('promotion', models.BooleanField()),
                ('rent', models.BooleanField()),
                ('wholesale', models.BooleanField()),
                ('likes', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('validated', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='items.Item')),
            ],
        ),
    ]
